using System.Text;

namespace Sidio.Mediator.SourceGenerator;

internal static class SourceGenerationHelper
{
    private const string Spacing = "    ";

    private const string ExcludeFromCodeCoverageAttribute = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";

    private const string ClassHeader =
"// <auto-generated/>\n" +
"#nullable enable\n" +
"#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member\n" +
"#pragma warning disable SA1600 // Elements should be documented\n";

    private static readonly string GeneratedCodeAttribute = $"[global::System.CodeDom.Compiler.GeneratedCode(\"Sidio.Mediator.SourceGenerator\", \"{GetAssemblyVersion()}\")]";

    public static readonly string MediatorPartialClassSource = ClassHeader + @"
namespace Sidio.Mediator
{
    "+GeneratedCodeAttribute+@"
    public partial interface IMediator
    {
    }

    "+GeneratedCodeAttribute+@"
    "+ExcludeFromCodeCoverageAttribute+@"
    public partial class Mediator : IMediator
    {
        private readonly global::System.IServiceProvider _serviceProvider;

        public Mediator(global::System.IServiceProvider serviceProvider)
        {
            if (serviceProvider == null)
            {
                throw new global::System.ArgumentNullException(nameof(serviceProvider));
            }

            _serviceProvider = serviceProvider;
        }
    }

    "+GeneratedCodeAttribute+@"
    "+ExcludeFromCodeCoverageAttribute+@"
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Adds the <see cref=""IMediator""/> service to the <see cref=""IServiceCollection""/>.
        /// </summary>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMediatorService(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)
        {
            if (services == null)
            {
                throw new global::System.ArgumentNullException(nameof(services));
            }

            var serviceDescriptor = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(IMediator), typeof(Mediator), lifetime);
            services.Add(serviceDescriptor);
            return services;
        }
    }
}";
    
    public static string GenerateClass(RequestToGenerate requestToGenerate)
    {
        var usings = new HashSet<string>();
        foreach(var u in requestToGenerate.Usings)
        {
            usings.Add(u);
        }

        if (!string.IsNullOrWhiteSpace(requestToGenerate.NamespaceName))
        {
            usings.Add(requestToGenerate.NamespaceName);
        }

        var httpPrefix = requestToGenerate.IsHttpRequest ? "Http.Http" : string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine(ClassHeader);
        sb.AppendLine("namespace Sidio.Mediator");
        sb.AppendLine("{");
        foreach (var u in usings)
        {
            sb.AppendLine($"{Spacing}using {u};");
        }

        // interface
        sb.AppendLine();
        sb.AppendLine($"{Spacing}public partial interface IMediator");
        sb.AppendLine($"{Spacing}{{");
        if (requestToGenerate.ReturnType is not null)
        {
            sb.AppendLine($"{Spacing}{Spacing}global::System.Threading.Tasks.Task<global::Sidio.Mediator.{httpPrefix}Result<{requestToGenerate.ReturnType}>> {requestToGenerate.ClassName}Async({requestToGenerate.ClassName} request, global::System.Threading.CancellationToken cancellationToken = default);");
        }
        else
        {
            sb.AppendLine($"{Spacing}{Spacing}global::System.Threading.Tasks.Task<global::Sidio.Mediator.Result> {requestToGenerate.ClassName}Async({requestToGenerate.ClassName} request, global::System.Threading.CancellationToken cancellationToken = default);");
        }

        sb.AppendLine($"{Spacing}}}\n"); // interface IMediator

        // class
        sb.AppendLine($"{Spacing}public partial class Mediator");
        sb.AppendLine($"{Spacing}{{");

        if (requestToGenerate.ReturnType is not null)
        {
            sb.AppendLine($"{Spacing}{Spacing}public global::System.Threading.Tasks.Task<global::Sidio.Mediator.{httpPrefix}Result<{requestToGenerate.ReturnType}>> {requestToGenerate.ClassName}Async({requestToGenerate.ClassName} request, global::System.Threading.CancellationToken cancellationToken = default)");
        }
        else
        {
            sb.AppendLine($"{Spacing}{Spacing}public global::System.Threading.Tasks.Task<global::Sidio.Mediator.Result> {requestToGenerate.ClassName}Async({requestToGenerate.ClassName} request, global::System.Threading.CancellationToken cancellationToken = default)");
        }

        sb.AppendLine($"{Spacing}{Spacing}{{");

        sb.AppendLine($"{Spacing}{Spacing}{Spacing}var requestHandler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{requestToGenerate.RequestHandlerInterface}>(_serviceProvider);");
        sb.AppendLine($"{Spacing}{Spacing}{Spacing}return requestHandler.HandleAsync(request, cancellationToken);");

        sb.AppendLine($"{Spacing}{Spacing}}}"); // function
        sb.AppendLine($"{Spacing}}}"); // class Mediator
        sb.AppendLine("}"); // namespace

        return sb.ToString();
    }

    private static string GetAssemblyVersion()
    {
        var assembly = typeof(SourceGenerationHelper).Assembly;
        var versionAttribute = assembly.GetCustomAttributes(
                typeof(System.Reflection.AssemblyInformationalVersionAttribute),
                false)
            .FirstOrDefault() as System.Reflection.AssemblyInformationalVersionAttribute;

        return (versionAttribute?.InformationalVersion ?? "1.0.0+unknown").Split('+')[0];
    }
}