//HintName: Mediator.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable SA1600 // Elements should be documented

namespace Sidio.Mediator
{
    [global::System.CodeDom.Compiler.GeneratedCode("Sidio.Mediator.SourceGenerator", "1.0.0")]
    public partial interface IMediator
    {
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Sidio.Mediator.SourceGenerator", "1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Mediator : IMediator
    {
        private readonly global::System.IServiceProvider _serviceProvider;

        public Mediator(global::System.IServiceProvider serviceProvider)
        {
            if (serviceProvider == null)
            {
                throw new global::System.ArgumentNullException(nameof(serviceProvider));
            }

            _serviceProvider = serviceProvider;
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Sidio.Mediator.SourceGenerator", "1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class ServiceCollectionExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMediatorService(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)
        {
            if (services == null)
            {
                throw new global::System.ArgumentNullException(nameof(services));
            }

            var serviceDescriptor = new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(IMediator), typeof(Mediator), lifetime);
            services.Add(serviceDescriptor);
            return services;
        }
    }
}