//HintName: Mediator.TestRequest1.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable SA1600 // Elements should be documented

namespace Sidio.Mediator
{
    using Sidio.Mediator.SourceGenerator.Tests;

    public partial interface IMediator
    {
        global::System.Threading.Tasks.Task<global::Sidio.Mediator.Result<string>> TestRequest1Async(TestRequest1 request, global::System.Threading.CancellationToken cancellationToken = default);
    }

    public partial class Mediator
    {
        public global::System.Threading.Tasks.Task<global::Sidio.Mediator.Result<string>> TestRequest1Async(TestRequest1 request, global::System.Threading.CancellationToken cancellationToken = default)
        {
            var requestHandler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sidio.Mediator.IRequestHandler<TestRequest1, string>>(_serviceProvider);
            return requestHandler.HandleAsync(request, cancellationToken);
        }
    }
}
