//HintName: Mediator.TestRequest1.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable SA1600 // Elements should be documented

namespace Sidio.Mediator
{
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using Sidio.Mediator.SourceGenerator.Tests;

    public partial interface IMediator
    {
        Task<Result> TestRequest1Async(TestRequest1 request, CancellationToken cancellationToken = default);
    }

    public partial class Mediator
    {
        public Task<Result> TestRequest1Async(TestRequest1 request, CancellationToken cancellationToken = default)
        {
            var requestHandler = _serviceProvider.GetRequiredService<IRequestHandler<TestRequest1>>();
            return requestHandler.HandleAsync(request, cancellationToken);
        }
    }
}
